[build-system]
requires = ["setuptools>=77.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "2dcomboselector"
version = "1.0.0"
description = "A Python tool for interactive 2D combination selection and analysis."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "Chapel-Saint-Auret" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "PySide6",
    "matplotlib",
    "numpy",
    "pandas",
    "scipy",
    "seaborn",
    "openpyxl",
    "markdown",
]

[project.urls]
Homepage = "https://github.com/Chapel-Saint-Auret/2dcomboselector"
Documentation = "https://2dcomboselector-docs.readthedocs.io/"
Issues = "https://github.com/Chapel-Saint-Auret/2dcomboselector/issues"
Changelog = "https://github.com/Chapel-Saint-Auret/2dcomboselector/blob/main/CHANGELOG.md"

[project.scripts]
combo-selector = "combo_selector.launcher:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
combo_selector = ["resources/**/*"]
