"""Regression tests for orthogonality-metric performance optimizations."""

from __future__ import annotations

import os
import unittest
from unittest.mock import patch

import pandas as pd

from combo_selector.core import metric_engine
from combo_selector.core.orthogonality_utils import compute_percent_fit_for_set

from tests.helpers import (
    CoreTestModel,
    make_retention_df_four_conditions,
    make_temp_workbook,
)


class MetricOptimizationTests(unittest.TestCase):
    """Ensure shared work is reused without changing metric outputs."""

    # Values generated by the implementation on main before the optimization.
    # Every list follows the deterministic Set 1 ... Set 6 fixture order.
    BASELINE_VALUES = {
        "bin_box_ratio": [1.0, 1.0, 0.75, 0.75, 1.0, 1.0],
        "gilar-watson": [
            0.7936507936507936,
            0.7936507936507936,
            0.3968253968253968,
            0.3968253968253968,
            0.7936507936507936,
            0.7936507936507936,
        ],
        "modeling_approach": [
            1.4444444444444442,
            1.4444444444444442,
            1.1428571428571428,
            0.42857142857142844,
            1.4444444444444442,
            1.5873015873015872,
        ],
        "nnd_arithmetic_mean": [
            0.9804550942671795,
            1.0796609462891447,
            1.0519586267955345,
            0.881249242245214,
            0.9804550942671795,
            0.9473533951387124,
        ],
        "nnd_geom_mean": [
            0.9628195304178433,
            1.0796609462891447,
            1.021080280521387,
            0.8586227475766917,
            0.9628195304178433,
            0.8628425576834418,
        ],
        "nnd_harm_mean": [
            0.9427009189933704,
            1.0796609462891447,
            0.9878618478191304,
            0.8365771989520837,
            0.9427009189933704,
            0.8051778107112362,
        ],
        "nnd_mean": [
            0.9619918478927977,
            1.0796609462891447,
            1.0203002517120174,
            0.8588163962579966,
            0.9619918478927977,
            0.87179125451113,
        ],
        "percent_fit": [
            0.5123728892197839,
            0.6092521224710322,
            0.6306386754093732,
            0.6425998382322673,
            0.5123728892197842,
            0.52410683976936,
        ],
    }

    def setUp(self) -> None:
        self.workbook = make_temp_workbook(
            {"Retention": make_retention_df_four_conditions()}
        )
        self.model = CoreTestModel()
        self.model.load_retention_time(self.workbook, "Retention")
        self.model.normalize_retention_time("min_max")

    def tearDown(self) -> None:
        if os.path.exists(self.workbook):
            os.remove(self.workbook)

    def test_grid_metrics_share_one_mask_per_set_and_bin_setting(self) -> None:
        set_count = len(self.model.orthogonality_dict)

        with patch.object(
            metric_engine,
            "compute_bin_box_mask_color",
            wraps=metric_engine.compute_bin_box_mask_color,
        ) as compute_mask:
            self.model.compute_bin_box()
            self.model.compute_gilar_watson_metric()
            self.model.compute_modeling_approach()

            self.assertEqual(compute_mask.call_count, set_count)

            self.model.update_num_bins(self.model.bin_number + 1)
            self.model.compute_bin_box()
            self.assertEqual(compute_mask.call_count, 2 * set_count)

    def test_nnd_mean_reuses_computed_component_metrics(self) -> None:
        self.model.compute_ndd()

        with patch.object(
            self.model, "compute_ndd", wraps=self.model.compute_ndd
        ) as compute_ndd:
            self.model.compute_nnd_mean()

        compute_ndd.assert_not_called()

    def test_percent_fit_keeps_regression_value(self) -> None:
        set_key, result = compute_percent_fit_for_set(
            "Set 1", self.model.orthogonality_dict["Set 1"]
        )

        self.assertEqual(set_key, "Set 1")
        self.assertAlmostEqual(
            result["percent_fit"]["value"], 0.5123728892197839, places=12
        )

    def test_all_optimized_metrics_match_baseline_values_and_ranks(self) -> None:
        self.model.compute_bin_box()
        self.model.compute_gilar_watson_metric()
        self.model.compute_modeling_approach()
        self.model.compute_ndd()
        self.model.compute_nnd_mean()
        self.model.compute_percent_fit()

        set_keys = list(self.model.orthogonality_dict)
        for metric, expected_values in self.BASELINE_VALUES.items():
            actual_values = [
                self.model.orthogonality_score[set_key][metric]
                for set_key in set_keys
            ]

            for actual, expected in zip(actual_values, expected_values):
                self.assertAlmostEqual(actual, expected, places=12, msg=metric)

            actual_ranks = pd.Series(actual_values).rank(
                ascending=False, method="average"
            )
            expected_ranks = pd.Series(expected_values).rank(
                ascending=False, method="average"
            )
            self.assertListEqual(actual_ranks.tolist(), expected_ranks.tolist())


if __name__ == "__main__":
    unittest.main()
